title: Chris McCreary
description: Hardware development, electrical test, rapid prototyping, and systems integration.
url: https://phoenixjack.github.io
repository: Phoenixjack/phoenixjack.github.io
theme: jekyll-theme-cayman
markdown: kramdown
show_downloads: false
